vim.api.nvim_exec([[ hi link @lsp.type.method Method]], true)
vim.api.nvim_exec([[ hi link @lsp.type.parameter Parameter]], true)
vim.api.nvim_exec([[ hi link @lsp.type.property Property]], true)
vim.api.nvim_exec([[ hi link @lsp.type.namespace Namespace]], true)
vim.api.nvim_exec([[ hi @lsp.type.enum guifg=#3084B4 gui=bold]], true)
vim.api.nvim_exec([[ hi @lsp.type.enumMember guifg=#00E2C8 gui=bold]], true)
vim.api.nvim_exec([[ hi rainbowcol1 guifg=#BDB76B ]], true)
